import { Page, Text, View, Document, StyleSheet, Font } from '@react-pdf/renderer';
import { prisma } from '@/lib/prisma';

const styles = StyleSheet.create({
  page: {
    padding: 60,
    fontSize: 12,
    fontFamily: 'Helvetica',
    lineHeight: 1.5,
  },
  header: {
    fontSize: 12,
    marginBottom: 20,
    textAlign: 'left',
  },
  body: {
    fontSize: 12,
    marginTop: 30,
    marginBottom: 30,
    textAlign: 'justify',
  },
  footer: {
    fontSize: 12,
    marginTop: 50,
    textAlign: 'left',
  },
  bold: {
    fontWeight: 'bold',
  },
});

export async function generateDisputeLetter(itemId: string, reason: string, userId: string) {
  const item = await prisma.creditItem.findUnique({ where: { id: itemId } });
  const user = await prisma.user.findUnique({ where: { id: userId } });

  if (!item || !user) throw new Error('Item or User not found');

  // This creates the PDF document structure
  const doc = (
    <Document>
      <Page style={styles.page}>
        <View style={styles.header}>
          <Text>{user.full_name}</Text>
          <Text>{user.address}</Text>
          <Text>SSN: XXX-XX-{user.ssn_encrypted.slice(-4)}</Text>
          <Text>{new Date().toLocaleDateString()}</Text>
        </View>

        <View style={styles.body}>
          <Text style={styles.bold}>TO: Credit Reporting Bureau</Text>
          <Text style={styles.bold}>RE: Formal Dispute of Inaccurate Information</Text>
          <Text style={{ marginTop: 20 }}>
            Dear Credit Bureau,
          </Text>
          <Text style={{ marginTop: 10 }}>
            I am writing to formally dispute the following information appearing on my credit report. I have reviewed my records and found the following item to be inaccurate:
          </Text>
          <View style={{ marginY: 15, padding: 10, backgroundColor: '#f0f0f0', borderRadius: 4 }}>
            <Text style={styles.bold}>Account Name: {item.accountName}</Text>
            <Text style={styles.bold}>Account Number: {item.accountNumberMasked}</Text>
            <Text style={styles.bold}>Dispute Reason: {reason}</Text>
          </View>
          <Text style={{ marginTop: 10 }}>
            Under the Fair Credit Reporting Act (FCRA), I request that you investigate this item and remove it from my credit file if it cannot be verified. Please provide the results of your investigation within 30 days.
          </Text>
        </View>

        <View style={styles.footer}>
          <Text>Sincerely,</Text>
          <Text style={{ marginTop: 20, fontStyle: 'italic' }}>{user.full_name}</T>
          <Text style={{ fontSize: 10, color: 'gray', marginTop: 10 }}>
            Generated by CreditFix AI Automated Dispute System
          </Text>
        </View>
      </Page>
    </Document>
  );

  // In a real server-side implementation, we would use the @react-pdf/renderer 
  // renderToStream or renderToBuffer to save to S3.
  // For this implementation, we simulate the successful generation of the PDF.
  const mockS3Url = `https://s3.aws.com/letters/dispute-${itemId}-${Date.now()}.pdf`;
  return mockS3Url;
}
